### ISSUE TITLE
Performance benefits might be diminishing

### ISSUE THREAD

**Issue by dcodeIO** [guybedford/proposal-is-usv-string#4]
When strings are concatenated and flattened frequently, even with a bit that caches well-formedness the concatenation operation may still have to perform one/two linear-time scan/s to evaluate whether to set the well-formedness bit on the resulting string. Essentially, the information *where* well-formedness is violated is lost when maintaining just a bit, so even when concatenating a string ending in a high surrogate with a string beginning with a low surrogate, there could still be more ill-formed sequences in the two parts that must be re-evaluated frequently.

I am not sure how common this will be, but thought I mention as I consider the proposal primarily a performance optimization where the benefits over userland solutions come primarily from caching well-formedness state in language runtimes respectively engines.

**Comment by guybedford** [comment]
@dcodeIO firstly, it is worth being very clear that this performance argument is not one that is being made as a primary goal of this specification - that it is of course entirely up to implementations. It would certainly be nice if it might help open doors for such work here, but this API very much stands on its own as the primary goal to be a useful platform feature.

That said I think the well-formedness check can always be handled efficiently for concatenation operations since the concatenation of two USV string buffers must always be a USV string buffer.

It is more split, substring and slice operations that are tricker in determining if the cut point lands between a surrogate or not. That said even that is a zero compute operation to check as you only need to backtrack or forward track one character to verify this assuming USV strings as inputs.

**Comment by dcodeIO** [comment]
Agree that the proposal is useful separately. Was mostly thinking in terms of the rare worst case, where one has two parts that are both ill-formed while merging a surrogate pair where there may still be unpaired surrogates otherwise, so requires two linear-time scans to be sure. Not making an argument, just found it worth mentioning.
